/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PBadge: typeof import('primevue/badge')['default']
    PButton: typeof import('primevue/button')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PIconField: typeof import('primevue/iconfield')['default']
    PInputIcon: typeof import('primevue/inputicon')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenu: typeof import('primevue/menu')['default']
    PPaginator: typeof import('primevue/paginator')['default']
    PTree: typeof import('primevue/tree')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
